import { sharedStyles, useSharedStyles } from "../styles/sharedStyles";

function adminApprovingGridPainting(props) {
  const classes = sharedStyles;
  const {
    username,
    name,
    lastName,
    email,
    phoneNumber,
    taxCode,
    dateOfBirth,
    roll,
  } = { ...props };

  const columns = [
    {
      headerName: " ",
      headerCheckboxSelection: true,
      checkboxSelection: true,
      floatingFilter: false,
      suppressMenu: true,
      minWidth: 55,
      maxWidth: 55,
      width: 55,
      flex: 0,
      resizable: false,
      sortable: false,
      editable: false,
      filter: false,
      suppressColumnsToolPanel: true,
    },
    {
      headerClass: classes.header,
      field: "clientId",
      headerName: "Client ID",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerClass: classes.header,
      field: "username",
      headerName: "User",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: username.panel,
      rowGroup: username.rowGroup,
      hide: username.hide,
      flex: username.flex,
    },
    {
      headerClass: classes.header,
      field: "name",
      headerName: "Name",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: name.panel,
      rowGroup: name.rowGroup,
      hide: name.hide,
      flex: name.flex,
    },
    {
      headerClass: classes.header,
      field: "lastName",
      headerName: "Last name",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: lastName.panel,
      rowGroup: lastName.rowGroup,
      hide: lastName.hide,
      flex: lastName.flex,
    },
    {
      headerClass: classes.header,
      field: "email",
      headerName: "email",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: email.panel,
      rowGroup: email.rowGroup,
      hide: email.hide,
      flex: email.flex,
    },
    {
      headerClass: classes.header,
      field: "phoneNumber",
      headerName: "Phone number",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: phoneNumber.panel,
      rowGroup: phoneNumber.rowGroup,
      hide: phoneNumber.hide,
      flex: phoneNumber.flex,
    },
    {
      headerClass: classes.header,
      field: "taxCode",
      headerName: "Tax code",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: taxCode.panel,
      rowGroup: taxCode.rowGroup,
      hide: taxCode.hide,
      flex: taxCode.flex,
    },
    {
      headerClass: classes.header,
      field: "dateOfBirth",
      headerName: "Date of birth",
      columnGroupShow: "closed",
      filter: "agDateColumnFilter",
      editable: false,
      suppressColumnsToolPanel: dateOfBirth.panel,
      rowGroup: dateOfBirth.rowGroup,
      hide: dateOfBirth.hide,
      flex: dateOfBirth.flex,
    },
    {
      headerClass: classes.header,
      field: "roll",
      headerName: "Roll",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: roll.panel,
      rowGroup: roll.rowGroup,
      hide: roll.hide,
      flex: roll.flex,
    },
  ];
  return columns;
}

export default adminApprovingGridPainting;
