import { sharedStyles } from "../styles/sharedStyles";

function GridColumns(props) {
  const classes = sharedStyles;
  const {
    checkbox,
    username,
    title,
    creationDate,
    description,
    notes,
    quantity,
    unit,
    costForUnit,
    totalCost,
    state,
    status,
  } = { ...props };

  const columns = [
    {
      headerName: " ",
      headerCheckboxSelection: checkbox,
      checkboxSelection: checkbox,
      floatingFilter: false,
      suppressMenu: true,
      minWidth: 55,
      maxWidth: 55,
      width: 55,
      flex: 0,
      resizable: false,
      sortable: false,
      editable: false,
      filter: false,
      suppressColumnsToolPanel: true,
    },
    {
      headerClass: classes.header,
      field: "clientId",
      headerName: "Client ID",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      hide: true,
      suppressColumnsToolPanel: true,
    },
    {
      headerClass: classes.header,
      field: "username",
      headerName: "User",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: username.panel,
      rowGroup: username.rowGroup,
      hide: username.hide,
      flex: username.flex,
    },
    {
      headerClass: classes.header,
      field: "title",
      headerName: "Task title",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: title.panel,
      rowGroup: title.rowGroup,
      hide: title.hide,
      flex: title.flex,
    },
    {
      headerClass: classes.header,
      field: "creationDate",
      headerName: "Creation date",
      columnGroupShow: "closed",
      filter: "agDateColumnFilter",
      editable: false,
      suppressColumnsToolPanel: creationDate.panel,
      rowGroup: creationDate.rowGroup,
      hide: creationDate.hide,
      flex: creationDate.flex,
    },
    {
      headerClass: classes.header,
      field: "description",
      headerName: "Task description",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: description.panel,
      rowGroup: description.rowGroup,
      hide: description.hide,
      flex: description.flex,
    },
    {
      headerClass: classes.header,
      field: "notes",
      headerName: "Notes",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: notes.panel,
      rowGroup: notes.rowGroup,
      hide: notes.hide,
      flex: notes.flex,
    },
    {
      headerClass: classes.header,
      field: "quantity",
      headerName: "Due date",
      columnGroupShow: "closed",
      filter: "gsNumberColumnFilter",
      editable: false,
      suppressColumnsToolPanel: quantity.panel,
      rowGroup: quantity.rowGroup,
      hide: quantity.hide,
      flex: quantity.flex,
    },
    {
      headerClass: classes.header,
      field: "unit",
      headerName: "Unit",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: unit.panel,
      rowGroup: unit.rowGroup,
      hide: unit.hide,
      flex: unit.flex,
    },
    {
      headerClass: classes.header,
      field: "costForUnit",
      headerName: "Unit cost",
      columnGroupShow: "closed",
      filter: "gsNumberColumnFilter",
      editable: false,
      suppressColumnsToolPanel: costForUnit.panel,
      rowGroup: costForUnit.rowGroup,
      hide: costForUnit.hide,
      flex: costForUnit.flex,
    },
    {
      headerClass: classes.header,
      field: "cost",
      headerName: "Total cost",
      columnGroupShow: "closed",
      filter: "gsNumberColumnFilter",
      editable: false,
      suppressColumnsToolPanel: totalCost.panel,
      rowGroup: totalCost.rowGroup,
      hide: totalCost.hide,
      flex: totalCost.flex,
    },
    {
      headerClass: classes.header,
      field: "state",
      headerName: "State",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: false,
      suppressColumnsToolPanel: state.panel,
      rowGroup: state.rowGroup,
      hide: state.hide,
      flex: state.flex,
    },
    {
      headerClass: classes.header,
      field: "status",
      headerName: "Status",
      columnGroupShow: "closed",
      filter: "agTextColumnFilter",
      editable: status.editable || false,
      suppressColumnsToolPanel: status.panel,
      rowGroup: status.rowGroup,
      hide: status.hide,
      flex: status.flex,
      cellEditorSelector: status.cellEditorSelector,
    },
  ];
  return columns;
}

export default GridColumns;
